name: Latest blog posts workflow
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # First RSS feed
      - name: Update README with Hashnode blog posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://sabinewern.hashnode.dev/rss.xml"
          comment_tag_name: "PRACTICAL_BLOG_LIST"
          retry_count: 3
          retry_wait_time: 300
          user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
          accept_header: "application/rss+xml, application/xml, text/xml, */*"
      
      # Second RSS feed
      - name: Update README with second blog posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://airesearch.hashnode.dev/rss.xml"
          comment_tag_name: "RESEARCH_BLOG_LIST"
          retry_count: 3
          retry_wait_time: 300
          user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
          accept_header: "application/rss+xml, application/xml, text/xml, */*"
